Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String
Resources:
  ApacheInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0a3c3a20c09d6f377
      InstanceType: t3.micro
      KeyName: cloudformationlj
      SecurityGroups:
        - !Ref SecurityGroupApacheInstance


      UserData: !Base64 |
        #!/bin/bash -xe
        dnf update -y
        dnf install -y httpd
        systemctl start httpd
        systemctl enable httpd
        echo "<h1>Hello World from user data</h1>" > /var/www/html/index.html

  SecurityGroupApacheInstance:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and HTTP
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80

  #KeyPairEC2:
  #  Type: AWS::EC2::KeyPair
  #  Properties:
  #    KeyName: cloudformationlj
  #    PublicKeyMaterial: key-0137ee75183feeb96
